name: Web CD

env:
  IMAGE_TAG: ghcr.io/arkantrust/rj45-web:latest
  CONTAINER_NAME: rj45-web
  PORT: 80
  API_URL: http://localhost:8080 # Change

on:
  push:
    paths:
      - 'web/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Build and push Docker image
      uses: ./.github/workflows/publish.yaml
      with:
        project: web
        tag: ${{ env.IMAGE_TAG }}

  deploy:
    runs-on: aws-vm
    steps:
    - name: Pull Docker image
      run: sudo docker pull ${{ env.IMAGE_TAG }}

    - name: Delete old Docker container
      run: sudo docker rm -f ${{ env.CONTAINER_NAME }} || true

    - name: Run Docker container 
      run: |
        sudo docker run -d -p ${{ env.PORT }}:${{ env.PORT }} --name ${{ env.CONTAINER_NAME }} \
        -e PORT=${{ env.PORT }} \
        -e API_URL=${{ env.API_URL }} \
        ${{ env.IMAGE_TAG }}

    - name: Check running container
        run: sudo docker ps