server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  devtools:
    livereload:
      enabled: true
    add-properties: true
  profiles:
    default: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  enable-spring-security: true
  show-login-endpoint: true
  api-docs:
    path: /api.json
  swagger-ui:
    path: /docs
    url: /api.json
