server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  devtools:
    livereload:
      enabled: true
    add-properties: true
  profiles:
    default: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /docs.json
  swagger-ui:
    path: /docs