name: Analytics CI

on:
    pull_request:
      paths:
        - 'analytics/**'
      branches:
        - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
        with:
          sparse-checkout: |
            analytics
          sparse-checkout-cone-mode: false
    
    - run: cd analytics

    - name: Set up Python 3.12
    uses: actions/setup-python@v5
    with:
      python-version: '3.12'

    - name: Debug Environment Info
        run: |
            python --version
            pip --version

    - name: Test the application
    run: python -m pytest tests # Change this to the actual test command