name: API CD

env:
  IMAGE_TAG: ghcr.io/arkantrust/rj45-api:latest
  CONTAINER_NAME: rj45-api
  PORT: 8080

on:
  push:
    paths:
      - 'api/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Build and push Docker image
      uses: ./.github/workflows/publish.yaml
      with:
        project: api
        tag: ${{ env.IMAGE_TAG }}

  deploy:
    runs-on: aws-vm
    steps:
    - name: Pull Docker image
      run: sudo docker pull ${{ env.IMAGE_TAG }}

    - name: Delete old Docker container
      run: sudo docker rm -f ${{ env.CONTAINER_NAME }} || true

    - name: Run Docker container 
      run: |
        sudo docker run -d -p ${{ env.PORT }}:${{ env.PORT }} --name ${{ env.CONTAINER_NAME }} \
        -e PORT=${{ env.PORT }} \
        -e DB_URL=${{ secrets.DB_URL }} \
        -e DB_USER=${{ secrets.DB_USER }} \
        -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
        -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
        ${{ env.IMAGE_TAG }}

    - name: Check running container
        run: sudo docker ps
