name: API CI

on:
  pull_request:
    paths:
      - 'api/**'
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    with:
    sparse-checkout: |
      api
    sparse-checkout-cone-mode: false
  
    run: cd api
    
    - name: Set up JDK 21 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        architecture: x64

    - name: Debug Environment Info
      run: |
        java --version
        mvn --version

    # - name: Test the application
      # run: mvn test

    - name: Build the application
    run: mvn package -DskipTests