name: rj45

services:
  api:
    container_name: rj45-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080' # host:container
    environment:
      - DB_URL=postgresql://rj45-db/db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - backend

  db:
    image: 'postgres:16'
    restart: unless-stopped
    container_name: rj45-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db:

networks:
  backend:
    driver: bridge