name: star

services:
  api:
    container_name: star-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080' # host:container
    environment:
      - DB_URL=postgresql://star-db/dev
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=SQ6LL2JjN8iIwvRHP2eOCp1b45DAg+orPYie+rjVHakxbz5Ti54XrZpwLjxTt+OY8mL/jyUZzCMG9OP3Pftl8s6FRuLMdbX+pvEBENnDOHEMoF/T2uZtghMpdrohletoeXGGDSITkysTFUZk3Oj28uGLKQC5OPJ03Vl2DQWXlgehgHDzKDT3bR1glTNRMidhIbadpfmMiJBA0eybFYyZrXuP1WvJHHMlKsgTCYhRl1jgK60G5XdeVYBaAhURV/JrAKmpZdaqB4IkdhkRkmTOrCC1mNxBOEnBfJFpY5N4M3nX2jqMayH/M7rHXLm1qgbnYEA3Qadq4TTij5/O7+Yaxg==
    depends_on:
      - db
    networks:
      - backend

  db:
    image: 'postgres:16'
    restart: unless-stopped
    container_name: star-db
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db:
    name: star-db

networks:
  backend:
    driver: bridge
    name: star-backend
